name: Java CI with Maven

on:
  push:
    branches: [ main ] # Triggers on pushes to the 'main' branch
  pull_request:
    branches: [ main ] # Triggers on pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest # The type of runner that the job will run on

    strategy:
      matrix:
        java: [ 11, 17, 21 ] # Test on different LTS Java versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to checkout your code

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin' # Use a common distribution like Temurin (Open-Source)
          cache: 'maven' # Caches Maven dependencies for faster builds

      # NOTE: Assuming your project root (where pom.xml is) is 'lab3-tdd-kata-warmup-bank'
      - name: Locate the Project Directory
        run: |
          echo "PROJECT_DIR=Exercise/lab3-tdd-kata-warmup-bank" >> $GITHUB_ENV
          
      - name: Build with Maven
        run: mvn -B package # The '-B' is for batch mode, which is good for CI
        working-directory: ${{ env.PROJECT_DIR }} # Run the command from the project root
        
      # Optional: Run tests only (if 'package' doesn't run them)
      # - name: Run Tests with Maven
      #   run: mvn test
      #   working-directory: ${{ env.PROJECT_DIR }}

      # Optional: Upload build artifacts (e.g., the resulting JAR/WAR file)
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: package-artifact
      #     path: ${{ env.PROJECT_DIR }}/target/*.jar # Adjust path as needed
