name: Independent Java Test Pipeline

on:
  push:
  pull_request:

jobs:
  # -----------------------------------------------------------------
  # JOB 1: Run StringCalculator Tests
  # -----------------------------------------------------------------
  test-string-calculator:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 17] # Use your preferred working Java version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Set Project Directory
        # Ensure the PROJECT_DIR is correctly defined
        run: echo "PROJECT_DIR=Exercise/lab3-tdd-kata-warmup-bank" >> $GITHUB_ENV

      - name: Run StringCalculator Tests Only
        # Use the 'test' goal with the 'includes' option to target a specific test package/file
        # ASSUMPTION: The test class is named 'StringCalculatorTest.java'
        run: mvn -B test -Dtest=**/StringCalculatorTest
        working-directory: ${{ env.PROJECT_DIR }}

  # -----------------------------------------------------------------
  # JOB 2: Run BankAccount/Lab3 Tests
  # -----------------------------------------------------------------
  test-bank-account:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]  # Should match the version used in the other job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Set Project Directory
        run: echo "PROJECT_DIR=Exercise/lab3-tdd-kata-warmup-bank" >> $GITHUB_ENV
        
      - name: Run BankAccount Tests Only
        # Use the 'test' goal with a different 'includes' option for the other tests
        # ASSUMPTION: All tests for the 'lab3' folder are in the 'lab3' package
        run: mvn -B test -Dtest=**/BankAccountTest
        working-directory: ${{ env.PROJECT_DIR }}
  # -----------------------------------------------------------------
  # JOB 3: Discover and Run All Lab Tests Automatically
  # -----------------------------------------------------------------
  test-all-labs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Tests in All Labs
        run: |
          for pom in Exercise/lab*/pom.xml; do
            echo "▶ Running tests in $(dirname "$pom")"
            mvn -B test -f "$pom"
          done
